name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  focal:
    name: Ubuntu Focal

    runs-on: ubuntu-latest
    container:
      image: 'ubuntu:20.04'

    steps:
    - name: install apt deps
      run: apt update && apt install --no-install-recommends -y curl g++ git python3-dev python3-pip
    - name: install pip deps
      run: python3 -m pip install -U pip wheel setuptools pytest pytest-cov
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: install alephzero python
      run: python3 -m pip install .
    - name: run tests
      run: python3 -m pytest --cov=a0 tests/
    # - name: generate coverage
    #   run: gcov -o build/temp.linux-x86_64-3.6/ module.cc
    # - name: upload coverage
    #   run: bash <(curl -s https://codecov.io/bash)


  lint:
    name: Lint

    runs-on: ubuntu-latest
    container:
      image: 'ubuntu:20.04'

    steps:
    - uses: actions/checkout@v2
    - name: install apt deps
      run: apt update && apt install --no-install-recommends -y python3-pip
    - name: install pip deps
      run: python3 -m pip install -U flake8 yapf
    - name: yapf
      run: python3 -m yapf -d -r -e alephzero .
    - name: flake8
      run: python3 -m flake8


  pip:
    name: Send to PyPI

    runs-on: ubuntu-latest
    container:
      image: 'quay.io/pypa/manylinux2014_x86_64'

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: install apt deps
      run: yum install -y gcc-c++.x86_64 python3-devel.x86_64

    - name: install pip deps
      run: python3 -m pip install -U auditwheel pybind11 setuptools wheel

    - name: build package
      run: python3 setup.py sdist bdist_wheel

    - name: auditwheel ???
      run: |
        for whl in dist/*-linux_x86_64.whl; do
          auditwheel repair "$whl" -w dist/
        done
        rm dist/*-linux_x86_64.whl

    - name: Publish distribution ðŸ“¦ to Test PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish distribution ðŸ“¦ to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
